version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
      target: development
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
