# 1. Specify the version for docker-compose.yml
version: "3.8"

# 2. Generate the services needed
services:
  redis:
    container_name: "redis"
    image: redis:6.2.7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    # Add a custom password (optional)
    command: redis-server
    # Persistent storage (Data persistent)
    volumes:
      - .docker/data/redis:/data
#
### Be able to persist data in Docker UI by:
#   redis:
#     container_name: "redis"
#     image: redis:6.2.7-alpine
#     restart: unless-stopped
#     ports:
#       - "6379:6379"
#     command: redis-server
#     volumes:
#       - redis-data:/data
# volumes:
#   redis-data:
